apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u29qsakme-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u29qsakme-go 
  name: u29qsakme-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: u29qsakme-go 
